### ISSUE TITLE
duplicated slash in ResourceURL

### ISSUE THREAD

**Issue by ochriste** [camptocamp/tilecloud-chain#201]
in complement of  #198, there is still a double slash problem in the generated ressource url in WMTSCapabilities.xml :

the following configuration:

```
    <cachename>:
        type: s3
        # the s3 bucket name
        bucket: <bucketname>
        # the used folder in the bucket [default to '']
        folder: <foldername>
        # for GetCapabilities
        # can includes %(bucket)s, %(folder)s and %(host)s comes from this cache
        http_url: https://%(host)s/%(bucket)s/%(folder)s
        hosts:
        - <url>
```

gives the following result in the WMTSCapabilities.xml:

```
<ResourceURL format="image/png" resourceType="tile" template="https://<url>/<bucketname>/<foldername>//1.0.0/<layername>/default//{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.png"/>
```

notice the double // in `<foldername>//1.0.0`

the generate_controller command:
`./bin/generate_controller --cache <cachename> --dump-config`

gives the following result (truncated): 

```
caches:
  <cachename>:
    bucket: <bucketname>
    folder: <foldername>/
    hosts: [<url>]
    http_url: https://%(host)s/%(bucket)s/%(folder)s/
    http_urls: false
    name: <cachename>
    region: eu-west-1
    type: s3
    wmtscapabilities_file: 1.0.0/WMTSCapabilities.xml
```

notice the trailing slash after `<foldername>`, which seems automatically added, and same with the trailing slash after `https://%(host)s/%(bucket)s/%(folder)s`
