### ISSUE TITLE
Add SQS config example

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/tilecloud-chain#73]
```
  generation:
    ...
    # The region where the SQS queue is
    sqs_region_name: eu-west-1
    # The sqs queue name that should already exists
    sqs_queue_name: the_name
```
